FROM ubuntu:24.04

RUN apt update && apt install -y openssh-server python3 sudo && rm -rf /var/lib/apt/lists/*

RUN useradd -m ansible && echo "ansible:ansible" | chpasswd && adduser ansible sudo

RUN mkdir /var/run/sshd

RUN mkdir -p /home/ansible/.ssh && chown ansible:ansible /home/ansible/.ssh

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
