FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    python3 python3-pip ansible openssh-client \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /ansible
CMD ["tail", "-f", "/dev/null"]
